package com.zerocm.jdcheckin.mapper;

import com.zerocm.jdcheckin.pojo.domain.JdCookie;
import com.zerocm.jdcheckin.pojo.domain.JdCookieExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface JdCookieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_cookie
     *
     * @mbggenerated
     */
    int countByExample(JdCookieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_cookie
     *
     * @mbggenerated
     */
    int deleteByExample(JdCookieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_cookie
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_cookie
     *
     * @mbggenerated
     */
    int insert(JdCookie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_cookie
     *
     * @mbggenerated
     */
    int insertSelective(JdCookie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_cookie
     *
     * @mbggenerated
     */
    List<JdCookie> selectByExample(JdCookieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_cookie
     *
     * @mbggenerated
     */
    JdCookie selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_cookie
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") JdCookie record, @Param("example") JdCookieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_cookie
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") JdCookie record, @Param("example") JdCookieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_cookie
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JdCookie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_cookie
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JdCookie record);

    List<JdCookie> selectAllCookie();
}