package com.zerocm.jdcheckin.pojo.domain;

import java.io.Serializable;

public class JdCookie implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_cookie.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_cookie.jdUsername
     *
     * @mbggenerated
     */
    private String jdusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_cookie.jdCookie
     *
     * @mbggenerated
     */
    private String jdcookie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_cookie.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_cookie.field1
     *
     * @mbggenerated
     */
    private String field1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_cookie.field2
     *
     * @mbggenerated
     */
    private String field2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_cookie.field3
     *
     * @mbggenerated
     */
    private String field3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jd_cookie
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_cookie.id
     *
     * @return the value of jd_cookie.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_cookie.id
     *
     * @param id the value for jd_cookie.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_cookie.jdUsername
     *
     * @return the value of jd_cookie.jdUsername
     *
     * @mbggenerated
     */
    public String getJdusername() {
        return jdusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_cookie.jdUsername
     *
     * @param jdusername the value for jd_cookie.jdUsername
     *
     * @mbggenerated
     */
    public void setJdusername(String jdusername) {
        this.jdusername = jdusername == null ? null : jdusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_cookie.jdCookie
     *
     * @return the value of jd_cookie.jdCookie
     *
     * @mbggenerated
     */
    public String getJdcookie() {
        return jdcookie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_cookie.jdCookie
     *
     * @param jdcookie the value for jd_cookie.jdCookie
     *
     * @mbggenerated
     */
    public void setJdcookie(String jdcookie) {
        this.jdcookie = jdcookie == null ? null : jdcookie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_cookie.remark
     *
     * @return the value of jd_cookie.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_cookie.remark
     *
     * @param remark the value for jd_cookie.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_cookie.field1
     *
     * @return the value of jd_cookie.field1
     *
     * @mbggenerated
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_cookie.field1
     *
     * @param field1 the value for jd_cookie.field1
     *
     * @mbggenerated
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_cookie.field2
     *
     * @return the value of jd_cookie.field2
     *
     * @mbggenerated
     */
    public String getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_cookie.field2
     *
     * @param field2 the value for jd_cookie.field2
     *
     * @mbggenerated
     */
    public void setField2(String field2) {
        this.field2 = field2 == null ? null : field2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_cookie.field3
     *
     * @return the value of jd_cookie.field3
     *
     * @mbggenerated
     */
    public String getField3() {
        return field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_cookie.field3
     *
     * @param field3 the value for jd_cookie.field3
     *
     * @mbggenerated
     */
    public void setField3(String field3) {
        this.field3 = field3 == null ? null : field3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_cookie
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", jdusername=").append(jdusername);
        sb.append(", jdcookie=").append(jdcookie);
        sb.append(", remark=").append(remark);
        sb.append(", field1=").append(field1);
        sb.append(", field2=").append(field2);
        sb.append(", field3=").append(field3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}